/**
 * Adjacent = the two outlines share at least one identical boundary segment at the source's
 * 6-decimal precision. A single shared corner vertex is not adjacency. That definition is
 * unchanged; what changed is where it runs. Measured over the full county: 129,011 adjacent
 * pairs, and 65,714 of the 65,953 mapped parcels (99.6%) have at least one neighbour.
 *
 * The index is precomputed at extract time by `scripts/fetch-parcels.mjs` and committed as
 * `public/data/rock-island-parcels.adjacency.json`, because building it in the browser over
 * 818,376 vertices is not viable. Keys are parcel ids (`String(OBJECTID)`), never PINs — PIN
 * is not unique county-wide.
 */
export type AdjacencyIndex = ReadonlyMap<string, ReadonlySet<string>>;

const EMPTY_NEIGHBOURS: ReadonlySet<string> = new Set();

/**
 * Turn the committed adjacency file into the runtime index. `rows[i]` holds the neighbour
 * row indices of row `i`, index-aligned with `ids`.
 *
 * A parcel with no neighbours is omitted from the map entirely, matching the behaviour of
 * the old in-browser builder, which only ever inserted parcels that had one; `connectedBlocks`
 * already falls back to `EMPTY_NEIGHBOURS`. An out-of-range index is skipped rather than
 * thrown on: the file is generated by our own script, and throwing here would blank the
 * whole map over one bad row.
 */
export function adjacencyFromRows(
  ids: readonly string[],
  rows: readonly (readonly number[])[],
): AdjacencyIndex {
  const neighbours = new Map<string, Set<string>>();

  for (let i = 0; i < rows.length; i += 1) {
    const id = ids[i];
    if (id === undefined) continue;
    const row = rows[i];
    if (!row || row.length === 0) continue;
    const set = new Set<string>();
    for (const index of row) {
      const other = ids[index];
      if (other === undefined || other === id) continue;
      set.add(other);
    }
    if (set.size > 0) neighbours.set(id, set);
  }

  return neighbours;
}

/**
 * A depth-first walk restricted to the supplied parcel ids, ignoring neighbours outside it.
 * Duplicate ids in the input are collapsed. Output is deterministic: each block's ids
 * sorted ascending, blocks sorted by size descending then by first id ascending. An id
 * with no neighbours inside the set is its own single-member block.
 */
export function connectedBlocks(pins: readonly string[], index: AdjacencyIndex): string[][] {
  const set = new Set(pins);
  const visited = new Set<string>();
  const blocks: string[][] = [];

  for (const start of set) {
    if (visited.has(start)) continue;
    const block: string[] = [];
    const stack = [start];
    visited.add(start);
    while (stack.length > 0) {
      const pin = stack.pop()!;
      block.push(pin);
      const neighbours = index.get(pin) ?? EMPTY_NEIGHBOURS;
      for (const neighbour of neighbours) {
        if (set.has(neighbour) && !visited.has(neighbour)) {
          visited.add(neighbour);
          stack.push(neighbour);
        }
      }
    }
    block.sort();
    blocks.push(block);
  }

  blocks.sort((a, b) => b.length - a.length || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  return blocks;
}
