"use client";

import type { ReactElement } from "react";

/** The small inline chip used next to campaign names, channel labels and message rows. */
export function SimulatedBadge(): ReactElement {
  return (
    <span
      data-testid="simulated-badge"
      className="rounded-sm border border-amber-500/60 bg-amber-500/10 px-1 py-0.5 text-[9px] font-semibold tracking-widest text-amber-700 uppercase dark:text-amber-300"
    >
      SIMULATED
    </span>
  );
}

/**
 * The full-sentence disclosure banner. Reused at the top of every campaigns surface —
 * this is the strongest, plainest statement of AC2 ("no real dispatch path exists") the
 * UI carries, so its copy is verbatim per the plan and must not be paraphrased.
 */
export function SimulationBanner(): ReactElement {
  return (
    <div className="rounded-lg border border-amber-500/40 bg-amber-500/5 p-3 text-xs leading-relaxed dark:border-amber-400/30">
      <p data-testid="simulation-banner">
        <strong>SIMULATED — nothing here is ever sent.</strong> Every message, delivery, click,
        reply and bounce on this page is generated by an in-app simulator. Owner email addresses
        use the reserved <code>.invalid</code> domain and phone numbers use the reserved 555-01xx
        range, so a value copied out of this screen cannot reach a real inbox or handset. Mailing
        addresses are the real Rock Island County tax-bill addresses and are labelled as such; no
        address is ever invented.
      </p>
    </div>
  );
}
