import { fnv1a32, NO_MAILING_ADDRESS_REASON, type Owner } from "@/lib/owners";
import type { Channel } from "@/lib/campaigns/model";

/**
 * Mocked contact channels for an owner, kept structurally separate from the
 * county-sourced `src/lib/owners.ts`. This module never reads `localStorage`, never
 * imports React, never `fetch`es — it is pure.
 */

export type Provenance = "mocked" | "county-source";

export type Destination =
  | {
      channel: Channel;
      value: string; // what the message is addressed to
      provenance: Provenance;
      sourceLabel: string; // the chip rendered next to the value
      mailable: true;
    }
  | {
      channel: Channel;
      value: null;
      provenance: Provenance;
      sourceLabel: string;
      mailable: false;
      reason: string; // why this owner cannot be reached on this channel
    };

export const MOCK_EMAIL_DOMAIN = "simulated.invalid";
export const MOCK_PHONE_PREFIX = "+1 (309) 555-01";
export const MOCKED_LABEL = "Mocked contact detail — generated by this app, not county data";
export const COUNTY_LABEL = "Rock Island County GIS — tax-bill address";

/** `ownerKey` already carries its hash suffix, so the address is unique per owner. */
export function mockedEmail(owner: Owner): string {
  return `${owner.ownerKey}@${MOCK_EMAIL_DOMAIN}`;
}

/** Area code 309 is the real Rock Island area code; `555-01xx` can never connect. */
export function mockedPhone(owner: Owner): string {
  return `${MOCK_PHONE_PREFIX}${String(fnv1a32(owner.ownerKey) % 100).padStart(2, "0")}`;
}

export function destinationFor(owner: Owner, channel: Channel): Destination {
  if (channel === "email") {
    return {
      channel,
      value: mockedEmail(owner),
      provenance: "mocked",
      sourceLabel: MOCKED_LABEL,
      mailable: true,
    };
  }

  if (channel === "sms") {
    return {
      channel,
      value: mockedPhone(owner),
      provenance: "mocked",
      sourceLabel: MOCKED_LABEL,
      mailable: true,
    };
  }

  // channel === "direct_mail" — the real county tax-bill address, never synthesised.
  if (owner.mailingStreet !== null) {
    const value = `${owner.mailingStreet}\n${owner.mailingCityStateZip ?? ""}`.trim();
    return {
      channel,
      value,
      provenance: "county-source",
      sourceLabel: COUNTY_LABEL,
      mailable: true,
    };
  }

  return {
    channel,
    value: null,
    provenance: "county-source",
    sourceLabel: COUNTY_LABEL,
    mailable: false,
    reason: NO_MAILING_ADDRESS_REASON,
  };
}
